/ros2_laser_scan_merger:
  ros__parameters:
    flip1: false
    flip2: true
    inverse1: false
    inverse2: false
    laser1Alpha: 0.0
    laser1AngleMax: 180.0
    laser1AngleMin: -180.0
    laser1B: 0
    laser1G: 0
    laser1R: 255
    laser1XOff: 0.0
    laser1YOff: 0.0
    laser1ZOff: 0.0
    laser2Alpha: 0.0
    laser2AngleMax: 180.0
    laser2AngleMin: -180.0
    laser2B: 0
    laser2G: 0
    laser2R: 255
    laser2XOff: 0.0
    laser2YOff: 0.0
    laser2ZOff: 0.0
    pointCloudTopic: cloud_in
    pointCloutFrameId: laser
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: best_effort
    scanTopic1: /lidar_scan
    scanTopic2: /range
    show1: true
    show2: true
    use_sim_time: true

/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.015523369424045086
    angle_max: 3.14
    angle_min: -3.14
    inf_epsilon: 1.0
    max_height: 1.0
    min_height: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 16
    range_max: 2.0
    range_min: 0.05
    scan_time: 0.0
    target_frame: laser
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: false
